### ISSUE TITLE
Package requirements

### ISSUE THREAD

**Issue by 6r1d** [Demindiro/logimu#11]
Hello, I've tried to build fresh `logimu` in Docker and it failed several times until I installed some packages.

I don't know Cargo well, but if it can detect the distro and recommend to install packages, that'd be great. Otherwise, those could be added in the `README.md`, so the whole build process is shortened with the length of packages to be installed.

Anyway, there's my list for now:

* `pkg-config`
* `libcairo-dev`
* `libpango1.0-dev`
* `libgtk-3-dev`
* `libxcb-shape0`
* `libxcb-xfixes0`
* `libxcb-shape0-dev`
* `libxcb-xfixes0-dev`

What is the preferable solution?

**Comment by 6r1d** [comment]
Example `Dockerfile` for the context (using Logimu as the username):

```Dockerfile
FROM debian:bullseye-20220418

RUN apt-get update && apt-get install -y curl wget bash git build-essential python python3 python3-pip pkg-config libcairo-dev libpango1.0-dev libgtk-3-dev libxcb-shape0 libxcb-xfixes0 libxcb-shape0-dev libxcb-xfixes0-dev

RUN useradd -ms /bin/bash -u 1000 logimu
RUN chown logimu:logimu /home/logimu
USER logimu

WORKDIR /home/logimu
```

Example `docker-compose.yml`:

```yaml
version: "3.2"

services:

  insulator:
    build:
      context: "./"
    command: ["/usr/bin/tail", "-F", "/nonexistent"]
    volumes:
      - ./userdir:/home/logimu
```
